# Локальная тема - светлая/яркая для визуального обозначения локальной работы
foreground #000000
background #ffffff
selection_foreground #ffffff
selection_background #0000ff

# Цвета текста
color0 #000000
color1 #cd0000
color2 #00cd00
color3 #cdcd00
color4 #0000ee
color5 #cd00cd
color6 #00cdcd
color7 #e5e5e5

# Яркие цвета
color8 #7f7f7f
color9 #ff0000
color10 #00ff00
color11 #ffff00
color12 #5c5cff
color13 #ff00ff
color14 #00ffff
color15 #ffffff

# Цвета окна
active_border_color #00ff00
inactive_border_color #cccccc
bell_border_color #ff0000

# Цвета вкладок
active_tab_foreground #000000
active_tab_background #00ff00
inactive_tab_foreground #444444
inactive_tab_background #aaaaaa

# URL
url_color #0000ff
